### ISSUE TITLE
[REQUEST] - Add CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by letsintegreat** [swciitg/flutter_hacktober_2022#12]
### Summary

As stated [here](https://hacktoberfest.com/participation/#:~:text=Add%20a%20CONTRIBUTING.md%20file%20with%20contribution%20guidelines%20to%20your%20repository.), it is necessary to add a `CONTRIBUTING.md` file to your repo if it is going to participate in hacktoberfest. Moreover, it is a good practice to have it for contributors.

There are a plenty of templates available online, using any such template, refactor information about contribution from [README](https://github.com/swciitg/flutter_hacktober_2022#contribution-guide-) to CONTRIBUTING.

**Comment by Hareesh-Nandigrama** [comment]
Thanks for the issue. Its not necessary to have a CONTRIBUTING.md for projects participating and the reason we didn't have one was to make the README sufficient for an absolute beginner to gain all info. Nevertheless, it is definitely a good practice and we're adding one.
