### ISSUE TITLE
Design the Post Details page

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/flutter_hacktober_2022#14]
### Summary

Create the page campus_ola 5 as given in the figma and redirect the user to this page when he presses any of the post tile in the home page(campus_ola 1).

#### NOTE: Do write comments wherever possible in your code

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by pratikagr** [comment]
Assign me

**Comment by Hareesh-Nandigrama** [comment]
@pratikagr you have also been assigned

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama can you send me the figma link?

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja you can refer the readme for the figma link

**Comment by ekakshjanweja** [comment]
> 

Ok thanks for the help will disturb if I need any more help😅

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama I tried running the app but there is an error regarding the google services .json file

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja you just need to add your app in firebase and add the Google json file

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama yaa i got it but my firebase limit is over i need to make a new account sorry

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama how do i login

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja create an account and login

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama One more thing I have to only create the UI right?

**Comment by Hareesh-Nandigrama** [comment]
Yes

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama I made a pr. Can you tell me if you can see it?
