### ISSUE TITLE
Fetch Home Page Data From Firebase

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/flutter_hacktober_2022#17]
### Summary

Integrate your app with firebase and then fetch the post data from cloud firestore in the home page.
Make sure you follow the data models as given in the [figma file](https://www.figma.com/file/V478qN81WQ0nGJi0QKtPJI/Campus-OLA-Design?node-id=0%3A1). You can add data manually in firebase's firestore database and test your app. The posts must be sorted according to nearest date first. Dates which have passed by need not be displayed in the home page.

#### NOTE: Do write comments wherever possible in your code

**Comment by ManojPadia** [comment]
@Hareesh-Nandigrama  I would like to work on this issue. Could you please assign it to me?

**Comment by Hareesh-Nandigrama** [comment]
Yes, you can work on it @ManojPadia

**Comment by ManojPadia** [comment]
@Hareesh-Nandigrama could you please provide more data like i have to create firebase database on my account or what?
