### ISSUE TITLE
Create the post and Search Page

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/flutter_hacktober_2022#19]
### Summary

Look at the design given in the README and create campus_ola_6. Redirect the user to this page when he presses the + floating action button in the home screen.
Also reuse all the elements used to create campus_ola_6 to make campus_ola_2. Redirect the user to this page when he presses the search icon in the app Bar.
Only the UI is expected from your side

**Comment by PalaVenkiReddy** [comment]
@Hareesh-Nandigrama please assign this issue to me

**Comment by Hareesh-Nandigrama** [comment]
You can work on this now @PalaVenkiReddy

**Comment by ekakshjanweja** [comment]
Can you assign this to me ?

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja this issue is already assigned. You can request the post detail page if you like.

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama post details page works for me can you assign me

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama is this issue still pending?

**Comment by Hareesh-Nandigrama** [comment]
Yes, do u wish to work on it @ekakshjanweja

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama I would sure love to work on it:)

**Comment by Hareesh-Nandigrama** [comment]
You have been assigned @ekakshjanweja

**Comment by ekakshjanweja** [comment]
@Hareesh-Nandigrama what kind of date picker do i use?

**Comment by Hareesh-Nandigrama** [comment]
Use any one you like, preferably scroll field

**Comment by HarshBhakkad** [comment]
Is the issue still pending?

**Comment by Hareesh-Nandigrama** [comment]
@HarshBhakkad it is already assigned to someone

**Comment by Hareesh-Nandigrama** [comment]
@ekakshjanweja try to complete it by eod or you will be unassigned

**Comment by tanisha-salvi** [comment]
is this issue still open? i would like to work on it.
@Hareesh-Nandigrama

**Comment by tanisha-salvi** [comment]
@Hareesh-Nandigrama should i create both campus_ola_6 and campus_ola_2?
