### ISSUE TITLE
[REQUEST] - Make separate file for decorations on widget

### ISSUE THREAD

**Issue by StrawHATDEEPAK** [swciitg/flutter_hacktober_2022#21]
### Summary

Hey @swciitg 
I was thinking to make the code shorter and making it more easy to update UI by refactoring the all decoration which is used continuosly in the widgets (for ex. TextFieldForm, etc) in a separate file lets say decoration.dart or style.dart. This will increase code readability, and make it easy for us to make changes to all the places from just one place instead of doing it separately in each place .

**Comment by ekakshjanweja** [comment]
@StrawHATDEEPAK can you assign this to me?
