### ISSUE TITLE
Recreate UI for Signup/Signin screens

### ISSUE THREAD

**Issue by Kunalpal215** [swciitg/flutter_hacktober_2022#3]
### Summary

The design for Signup/Screens is very basic. You need to redesign and revamp the code for both screens. Follow this [url](https://www.figma.com/file/V478qN81WQ0nGJi0QKtPJI/Campus-OLA-Design?node-id=0%3A1) to see actual screen designs.

**Comment by tanisha-salvi** [comment]
I can redesign signup and signin screens, kindly assign this work to me.

**Comment by Hareesh-Nandigrama** [comment]
@tanisha-salvi you can work on it
