### ISSUE TITLE
Create AppBar for Home Screen

### ISSUE THREAD

**Issue by Kunalpal215** [swciitg/flutter_hacktober_2022#4]
### Summary

Look at the design given in README of this project and code the AppBar component and integrate it in home screen.
**NOTE: Write necessary comments in your code wherever possible.**

**Comment by Chaitanya-087** [comment]
i would like to work on this

**Comment by Shanta-11** [comment]
Would like to work on this. Can you assign it to me?

**Comment by Hareesh-Nandigrama** [comment]
@Shanta-11 yes you can work on it

**Comment by Hareesh-Nandigrama** [comment]
@Shanta-11 Try to complete this issue by tomorrow noon else it will be assigned to someone else

**Comment by Shanta-11** [comment]
![image](https://user-images.githubusercontent.com/103122644/194634537-93812e02-37a6-4b60-a794-4003b390edf2.png)

is this fine?

**Comment by Hareesh-Nandigrama** [comment]
![image](https://user-images.githubusercontent.com/85237630/194635180-6669fb58-cd83-45f3-ad89-968cff0d1333.png)
Your app bar must be as shown above. Check the fonts, colors and icons in the figma and create the pull request accordingly

**Comment by PalaVenkiReddy** [comment]
Can you please assign this to me?

**Comment by Hareesh-Nandigrama** [comment]
@PalaVenkiReddy you can work on this issue now
