### ISSUE TITLE
Code Create Post Button

### ISSUE THREAD

**Issue by Kunalpal215** [swciitg/flutter_hacktober_2022#5]
### Summary

Look at the design given in README for the home screen and add a floating action button for it and it should redirect to a new screen on click.

#### NOTE: Do write comments wherever possible in your code

**Comment by ShivamMenda** [comment]
Can I work on this @Kunalpal215?

**Comment by Hareesh-Nandigrama** [comment]
Yes you can work on it @ShivamMenda

**Comment by ShivamMenda** [comment]
@Hareesh-Nandigrama Okay only the button right?

**Comment by Hareesh-Nandigrama** [comment]
@ShivamMenda The button as well as the screen Campus ola-6 as given in the figma design, just the UI part

**Comment by Kunalpal215** [comment]
@ShivamMenda will you be able to complete this issue in next 24 hrs ?? If not, then, we will have to assign it to someone else. Please repond :).

**Comment by ShivamMenda** [comment]
Hey @Kunalpal215 I'm really sorry but I'm busy maintaining other repos you can assign to someone else.

**Comment by Hareesh-Nandigrama** [comment]
This issue is now open to be worked on
