### ISSUE TITLE
Create Home Page Design

### ISSUE THREAD

**Issue by Hareesh-Nandigrama** [swciitg/flutter_hacktober_2022#6]
### Summary

Look at the design given in README of this project and code the UI components(apart from the app bar) and integrate it in home screen.
NOTE: Write necessary comments in your code wherever possible.

**Comment by letsintegreat** [comment]
I'd like to work on this issue. If I am not wrong, I just need to design the `Campus ola 1` frame of the figma file, as the repo has different issues for AppBar and Floating Button, am I right?
