### ISSUE TITLE
[BUG] - The method 'showSnackBar' isn't defined for the type 'ScaffoldState'.

### ISSUE THREAD

**Issue by letsintegreat** [swciitg/flutter_hacktober_2022#8]
### Description

    Scaffold.of(builderContext).showSnackBar(SnackBar(content: Text(err.toString())));

A simple fix is to replace `Scaffold` with `ScaffoldMessenger` in both the files.

### Reproduction steps

```bash
1. Go to `lib/screens/auth/signin.dart`
2. Scroll down to line no. 92
3. See error

OR

1. Go to `lib/screens/auth/signup.dart`
2. Scroll down to line no. 149
3. See error
```

### Screenshots

![image](https://user-images.githubusercontent.com/37345795/194439293-0b332b69-d730-4a86-90ca-a1946f163b94.png)
![image](https://user-images.githubusercontent.com/37345795/194439325-881fae15-05b4-41d7-9443-a9c739abbde6.png)

### Platform

Android

**Comment by mauryakshitij** [comment]
Please assign this issue to me
